www/models/SearchForm.php
<?php
/**
 * Created by PhpStorm.
 * User: German
 * Date: 10/02/2019
 * Time: 08:41
 */

namespace app\models;
use yii\base\Model;


class SearchForm extends Model
{
    public $search;

    public function rules()
    {
        return [

        ];
    }
}

www/controllers/BasketController.php
<?php
/**
 * Created by PhpStorm.
 * User: German
 * Date: 20/02/2019
 * Time: 23:27
 */

namespace app\controllers;


use yii\web\Controller;
use app\models\Products;
use app\models\Basket;
use app\models\OrderItems;
use app\models\Orders;
use app\components\Pay2MeApi;
use Yii;

class BasketController extends Controller
{
    public function actionAdd(){
        $id = Yii::$app->request->get('id');
        $quantity =  abs((int)Yii::$app->request->get('quantity'));
        $quantity = !$quantity ? 1 : $quantity ;
        $product = Products::findOne($id);
        if (empty($product)){
            return false;
        }
        $session = Yii::$app->session;
        $session->open();
        $basket = new Basket();
        $basket->addToBasket($product,$quantity);
        $this->layout = false;
        if(!Yii::$app->request->isAjax){
            return $this->redirect(Yii::$app->request->referrer);
        }
        return $this->render('basket-modal',compact('session','quantity'));
    }

    public function actionClear(){
        $session = Yii::$app->session;
        $session->open();
        $session->remove('basket');
        $session->remove('basket.quantity');
        $session->remove('basket.sum');
        $this->layout = false;
        return $this->render('basket-modal',compact('session'));
    }

    public function actionDelItem(){
        $id = Yii::$app->request->get('id');
        $session = Yii::$app->session;
        $session->open();
        $basket = new Basket();
        $basket->recalc($id);
        $this->layout = false;
        return $this->render('basket-modal', compact('session'));

    }

    public function actionDelItemView(){
        $id = Yii::$app->request->get('id');
        $session = Yii::$app->session;
        $session->open();
        $basket = new Basket();
        $basket->recalc($id);
        $this->layout = false;
        return $this->render('view', compact('session'));

    }

    public function actionShow(){
        $session = Yii::$app->session;
        $session->open();
        $this->layout = false;
        return $this->render('basket-modal', compact('session'));
    }

    public function actionView(){
        $session = Yii::$app->session;
        $session->open();

        $order = new Orders();
        if($order->load(Yii::$app->request->post())) {
            $order->qty = $session['basket.quantity'];
            $order->sum = $session['basket.sum'];
            if (!$order->payment){
                $order->status = "cash";
                $order->order_desc = 'Наличные';
                if($order->save()){
                    $this->saveOrderItems($session['basket'], $order->order_code);
                    $session->removeAll();
                    return $this->render('success-pay');
                }
            }
            if ($order->payment) {
                return $this->payme($order);
            }
        }
        return $this->render('view',compact('session','order'));
    }

    protected function payme($order){
        $session = Yii::$app->session;
        $session->open();
        $pay2me = new Pay2MeApi();
        $order->order_desc= "Оплата заказа";
        if($order->save()) {
            $result = $pay2me->dealCreate($order->order_code, $order->order_desc, $order->sum, 0);
            $order->signature = $result->signature;
            $order->status = $result->status;
            $order->save();
            $this->saveOrderItems($session['basket'], $order->order_code);
            return $this->redirect($result->redirect);
        }
        return $this->render('error-pay');
    }

    public function actionPayResult(){
        $result = $_POST;
        $_SESSION['order_id'] = $result['order_id'];
        $_SESSION['pay_status'] = $result['status'];
    }

    public function actionSuccessPay(){
        $session = Yii::$app->session;
        $session->open();
        $order = Orders::findOne($_SESSION['order_id']);
        $order->status = $_SESSION['pay_status'];
        $session->removeAll();
        return $this->render('success-pay');
    }


    public function actionErrorPay(){
        return $this->render('error-pay');
    }

    protected function saveOrderItems($items,$order_code){
        foreach ($items as $id=>$item){
            $order_items = new OrderItems();
            $order_items->order_code = $order_code;
            $order_items->prod_code = $id;
            $order_items->prod_title = $item['title'];
            $order_items->price = $item['price'];
            $order_items->qty_item = $item['quantity'];
            $order_items->sum_item = $item['price']*$item['quantity'];
            $order_items->save();
        }
    }




    public function actionRefresh(){
        $session = ['sum'=> (isset($_SESSION['basket.sum'])) ? $_SESSION['basket.sum']: 0];

        return '<p>'.$session['sum']. ' ₽ </p>';
    }
}

www/controllers/ProductController.php
<?php
/**
 * Created by PhpStorm.
 * User: German
 * Date: 18/02/2019
 * Time: 20:13
 */

namespace app\controllers;


use app\models\Products;
use yii\web\Controller;

class ProductController extends Controller
{

    public function actionView($id){
        $product = Products::findOne($id);
        return $this->render('view',compact('product'));
    }

}

www/controllers/SearchController.php
<?php
/**
 * Created by PhpStorm.
 * User: German
 * Date: 14/02/2019
 * Time: 20:03
 */

namespace app\controllers;

use app\models\Categories;
use yii\data\Pagination;
use yii\web\Controller;
use app\models\Products;
use Yii;

class SearchController extends Controller
{
    public function actionCategory($id){
        $search = Categories::findOne($id)['category'];
        $query = Products::find()->where(['cat_num' => $id]);
        $pages = new Pagination(['totalCount'=>$query->count(), 'pageSize' => 8]);
        $products = $query->offset($pages->offset)->limit($pages->limit)->all();
        return  $this->render('category',compact('products','pages','search'));
    }

    public function actionTitle()
    {
        $search = trim(Yii::$app->request->get('SearchForm')['search']);

        if (!empty($search)) {
            $query1 = Products::find()->where(['like', 'title', $search]);
            $pages = new Pagination(['totalCount' => $query1->count(), 'pageSize' => 8, 'forcePageParam' => false, 'pageSizeParam' => false]);
            $products = $query1->offset($pages->offset)->limit($pages->limit)->all();

            if (empty($products)) {
                $query2 = Products::find()->where(['cat_num' => Categories::find()->where(['like', 'category', $search])->one()['cat_num']]);
                $pages = new Pagination(['totalCount' => $query2->count(), 'pageSize' => 8, 'forcePageParam' => false, 'pageSizeParam' => false]);
                $products = $query2->offset($pages->offset)->limit($pages->limit)->all();
                return $this->render('category', compact('products', 'pages', 'search'));
            }
            return $this->render('category', compact('products', 'pages', 'search'));
        } else {
            return $this->redirect(Yii::$app->request->referrer);
        }
    }

}

www/views/search/category.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
$this->title = $search;


?>

<?php if(!empty($products)): ?>

    <?php $i = 0 ?>

    <?php foreach ($products as $product):?>

        <?php if($i%4 === 0):?>
            <div class="row">
        <?php endif; ?>

        <div class="col-3 text-center">
        <a class="a" href="<?= Url::to(['product/view', 'id' => $product['code']])?>">
            <div class="product_mini cursor-pointer block-shadow">

                <div class="product_mini__buy text-center ">
                    <h4 class="product_mini__info__title"><?= $product['title'] ?></h4>
                    <p class="product_mini__price"><?= $product['price']?> ₽</p>
                    <p class="product_mini__descrip"><?= $product['description']?></p>
                    <object><a data-id="<?= $product['code']?>" class="product_mini__but btn add-to-basket" href="<?=Url::to(['basket/add','id'=>$product['code']]) ?>">В корзину <i class="fas fa-shopping-basket"></i></a></object>
                </div>

                <?= Html::img('@web/img/goods/'.$product['picture'],['class'=>'product_mini__picture']) ?>
                 <div class="product_mini__info text-left">
                    <h4 class="product_mini__title"><?= $product['title'] ?></h4>
                     <?php if($product['in_stock']===1): ?>
                        <p class="product_mini__inStock"><i class="fas fa-check green_fas"></i> Есть в наличии</p>
                     <?php else: ?>
                        <p class="product_mini__inStock"><i class="fas fa-times red_fas"></i> Нет в наличии</p>
                     <?php endif; ?>
                    <p class="product_mini__price"><?= $product['price']?> ₽</p>
                 </div>
            </div>
        </a>
        </div>

        <?php $i += 1; ?>

        <?php if($i%4 === 0):?>
            </div>
        <?php endif; ?>



    <?php endforeach; ?>

    <?php if($i%4 !== 0):?>
        </div>
    <?php endif; ?>
    <div style="margin-bottom: 20px" class="text-center">
    <?php
    echo \yii\widgets\LinkPager::widget([
        'pagination'=>$pages,
    ])
    ?>
    </div>

<?php else:?>
    <div class="empty_search text-center">
        <h2>Таких товаров пока нет :(</h2>
        <p>Возможно, вы ввели некорректный запрос. Если вы не смогли найти товар, в котором  нуждаетесь - обратитесь в администрацию магазина.</p>
    </div>
<?php endif; ?>