www/controllers/BasketController.php
<?php
/**
 * Created by PhpStorm.
 * User: German
 * Date: 20/02/2019
 * Time: 23:27
 */

namespace app\controllers;


use yii\web\Controller;
use app\models\Products;
use app\models\Basket;
use app\models\OrderItems;
use app\models\Orders;
use app\components\Pay2MeApi;
use Yii;

class BasketController extends Controller
{
    public function actionAdd(){
        $id = Yii::$app->request->get('id');
        $quantity =  abs((int)Yii::$app->request->get('quantity'));
        $quantity = !$quantity ? 1 : $quantity ;
        $product = Products::findOne($id);
        if (empty($product)){
            return false;
        }
        $session = Yii::$app->session;
        $session->open();
        $basket = new Basket();
        $basket->addToBasket($product,$quantity);
        $this->layout = false;
        if(!Yii::$app->request->isAjax){
            return $this->redirect(Yii::$app->request->referrer);
        }
        return $this->render('basket-modal',compact('session','quantity'));
    }

    public function actionClear(){
        $session = Yii::$app->session;
        $session->open();
        $session->remove('basket');
        $session->remove('basket.quantity');
        $session->remove('basket.sum');
        $this->layout = false;
        return $this->render('basket-modal',compact('session'));
    }

    public function actionDelItem(){
        $id = Yii::$app->request->get('id');
        $session = Yii::$app->session;
        $session->open();
        $basket = new Basket();
        $basket->recalc($id);
        $this->layout = false;
        return $this->render('basket-modal', compact('session'));

    }

    public function actionDelItemView(){
        $id = Yii::$app->request->get('id');
        $session = Yii::$app->session;
        $session->open();
        $basket = new Basket();
        $basket->recalc($id);
        $this->layout = false;
        return $this->render('view', compact('session'));

    }

    public function actionShow(){
        $session = Yii::$app->session;
        $session->open();
        $this->layout = false;
        return $this->render('basket-modal', compact('session'));
    }

    public function actionView(){
        $session = Yii::$app->session;
        $session->open();

        $order = new Orders();
        if($order->load(Yii::$app->request->post())) {
            $order->qty = $session['basket.quantity'];
            $order->sum = $session['basket.sum'];
            if (!$order->payment){
                $order->status = "cash";
                $order->order_desc = 'Наличные';
                if($order->save()){
                    $this->saveOrderItems($session['basket'], $order->order_code);
                    $session->removeAll();
                    return $this->render('success-pay');
                }
            }
            if ($order->payment) {
                return $this->payme($order);
            }
        }
        return $this->render('view',compact('session','order'));
    }

    protected function payme($order){
        $session = Yii::$app->session;
        $session->open();
        $pay2me = new Pay2MeApi();
        $order->order_desc= "Оплата заказа";
        if($order->save()) {
            $result = $pay2me->dealCreate($order->order_code, $order->order_desc, $order->sum, 0);
            $order->signature = $result->signature;
            $order->status = $result->status;
            $order->save();
            $this->saveOrderItems($session['basket'], $order->order_code);
            return $this->redirect($result->redirect);
        }
        return $this->render('error-pay');
    }

    public function actionPayResult(){
        $result = $_POST;
        $_SESSION['order_id'] = $result['order_id'];
        $_SESSION['pay_status'] = $result['status'];
    }

    public function actionSuccessPay(){
        $session = Yii::$app->session;
        $session->open();
        $order = Orders::findOne($_SESSION['order_id']);
        $order->status = $_SESSION['pay_status'];
        $session->removeAll();
        return $this->render('success-pay');
    }


    public function actionErrorPay(){
        return $this->render('error-pay');
    }

    protected function saveOrderItems($items,$order_code){
        foreach ($items as $id=>$item){
            $order_items = new OrderItems();
            $order_items->order_code = $order_code;
            $order_items->prod_code = $id;
            $order_items->prod_title = $item['title'];
            $order_items->price = $item['price'];
            $order_items->qty_item = $item['quantity'];
            $order_items->sum_item = $item['price']*$item['quantity'];
            $order_items->save();
        }
    }




    public function actionRefresh(){
        $session = ['sum'=> (isset($_SESSION['basket.sum'])) ? $_SESSION['basket.sum']: 0];

        return '<p>'.$session['sum']. ' ₽ </p>';
    }
}

www/controllers/MainController.php
<?php
/**
 * Created by PhpStorm.
 * User: German
 * Date: 09/02/2019
 * Time: 07:18
 */

namespace app\controllers;

use yii\web\Controller;
use app\models\Products;

class MainController extends Controller
{
    public function actionIndex()
    {
        $this->view->title = 'Dexytech';
        $products_sale = Products::find()->where(['sale' => 1])->limit(8)->all();
        $products_popular = Products::find()->where(['popular' => 1])->limit(8)->all();
       return $this->render('index',compact('products_sale','products_popular'));
    }
}

www/controllers/SearchController.php
<?php
/**
 * Created by PhpStorm.
 * User: German
 * Date: 14/02/2019
 * Time: 20:03
 */

namespace app\controllers;

use app\models\Categories;
use yii\data\Pagination;
use yii\web\Controller;
use app\models\Products;
use Yii;

class SearchController extends Controller
{
    public function actionCategory($id){
        $search = Categories::findOne($id)['category'];
        $query = Products::find()->where(['cat_num' => $id]);
        $pages = new Pagination(['totalCount'=>$query->count(), 'pageSize' => 8]);
        $products = $query->offset($pages->offset)->limit($pages->limit)->all();
        return  $this->render('category',compact('products','pages','search'));
    }

    public function actionTitle()
    {
        $search = trim(Yii::$app->request->get('SearchForm')['search']);

        if (!empty($search)) {
            $query1 = Products::find()->where(['like', 'title', $search]);
            $pages = new Pagination(['totalCount' => $query1->count(), 'pageSize' => 8, 'forcePageParam' => false, 'pageSizeParam' => false]);
            $products = $query1->offset($pages->offset)->limit($pages->limit)->all();

            if (empty($products)) {
                $query2 = Products::find()->where(['cat_num' => Categories::find()->where(['like', 'category', $search])->one()['cat_num']]);
                $pages = new Pagination(['totalCount' => $query2->count(), 'pageSize' => 8, 'forcePageParam' => false, 'pageSizeParam' => false]);
                $products = $query2->offset($pages->offset)->limit($pages->limit)->all();
                return $this->render('category', compact('products', 'pages', 'search'));
            }
            return $this->render('category', compact('products', 'pages', 'search'));
        } else {
            return $this->redirect(Yii::$app->request->referrer);
        }
    }

}

www/views/layouts/_main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use app\widgets\Alert;
use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap">
    <?php
    NavBar::begin([
        'brandLabel' => Yii::$app->name,
        'brandUrl' => Yii::$app->homeUrl,
        'options' => [
            'class' => 'navbar-inverse navbar-fixed-top',
        ],
    ]);
    echo Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-right'],
        'items' => [
            ['label' => 'Home', 'url' => ['/site/index']],
            ['label' => 'About', 'url' => ['/site/about']],
            ['label' => 'Contact', 'url' => ['/site/contact']],
            Yii::$app->user->isGuest ? (
                ['label' => 'Login', 'url' => ['/site/login']]
            ) : (
                '<li>'
                . Html::beginForm(['/site/logout'], 'post')
                . Html::submitButton(
                    'Logout (' . Yii::$app->user->identity->username . ')',
                    ['class' => 'btn btn-link logout']
                )
                . Html::endForm()
                . '</li>'
            )
        ],
    ]);
    NavBar::end();
    ?>

    <div class="container">
        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?= Alert::widget() ?>
        <?= $content ?>
    </div>
</div>

<footer class="footer">
    <div class="container">
        <p class="pull-left">&copy; My Company <?= date('Y') ?></p>

        <p class="pull-right"><?= Yii::powered() ?></p>
    </div>
</footer>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>


<div class="product">
    <?= Html::img('@web/'.$product['picture'],['class'=>'product__picture']) ?>
    <div class="product__title">
        <h3><?= $product['title'] ?></h3>
    </div>
    <div class="product__price">
        <p><?= $product['price']?></p>
    </div>
</div>

www/views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use app\widgets\Alert;
use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;
use app\assets\LtAppAsset;
use app\models\SearchForm;
use yii\widgets\ActiveForm;
use yii\helpers\Url;
use yii\widgets\ActiveField;
use app\models\Categories;

AppAsset::register($this);
LtAppAsset::register($this);
?>

<!DOCTYPE html>
<?php $this->beginPage() ?>
<html lang="<?= Yii::$app->language ?>">

<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://fonts.googleapis.com/css?family=Amatic+SC|Comfortaa|Montserrat" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.1/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
    <?php $this->head() ?>
</head><!--/head-->
<body>
<?php $this->beginBody() ?>
<header>
<section class="main-menu">
    <div class="container">
        <div class="row main-menu__row">
            <div class="col-3 main-menu__item text-center">

                <a href="<?= Url::to(['main/index'])?>" class="a">Главная</a>

            </div>
            <div class="col-3  main-menu__item text-center">

                <a href="" class="a">Доставка</a>

            </div>
            <div class="col-3  main-menu__item text-center">

                <a href="" class="a">Контакты</a>

            </div>
            <div class="col-3 main-menu__item no-border text-center">

                <a href="" class="a">О нас</a>

            </div>
        </div>
    </div>
</section>
<section class="contacts-section">
    <div class="container">
        <div class="row">
            <div class="col-4">
                <a href="<?= Url::to(['main/index'])?>" class="a"><?= Html::img('@web/img/logo_dexy.png', ['class'=>'logo', 'alt'=>'logo']) ?></a>
            </div>
            <div class="col-4"></div>
            <div class="col-2 text-right">
                <i class="fas fa-shopping-basket cursor-pointer basket-icon basket__icon"></i>
            </div>
            <div class="col-2 basket-icon__info basket__icon  cursor-pointer">
                <h4>Корзина:</h4>
                <div class="basket-icon__numbers basket__icon cursor-pointer">
                    <p><?= (isset($_SESSION['basket.sum'])) ? $_SESSION['basket.sum']: 0 ?> ₽</p>
                </div>
            </div>
        </div>
    </div>
</section>
<section class="search-section">
    <div class="container">
         <div class="row">
             <div class="col-2"></div>
             <div class="col-8">
                 <?php
                 $model = new SearchForm();
                 ?>
                 <?php $form = ActiveForm::begin([
                     'method'=>'get',
                     'action' => \yii\helpers\Url::to(['search/title']),
                     'options' => [
                         'class' => 'search'
                     ]
                 ]) ?>
                 <?= $form->field($model,'search')->label('')->textInput(['placeholder'=>'Поиск на сайте', 'class'=>'search__text']); ?>

                 <?php ActiveForm::end() ?>
             </div>
             <div class="col-2">
             </div>
         </div>
    </div>
</section>
<section class="categories">
        <div class="container">
            <div class="row">
                <div class="col-1 cursor-pointer">

                </div>
                <div class="col-2">
                    <div class="categories__menu">
                        <p class="cursor-pointer"><i class="fas fa-bars"></i> Каталог</p>
                        <ul>
                            <?=\app\widgets\CategoryWidget::widget()?>
                        </ul>
                    </div>
                </div>

                <div class="col-3 cursor-pointer">

                </div>
                <div class="col-3 cursor-pointer">

                </div>
                <div class="col-3 cursor-pointer">

                </div>
            </div>
        </div>
</section>
</header>
<main class="main">
    <div class="container">

    <?= $content; ?>

    </div>
</main>

<footer class="footer">
    <div class="container">
        <div class="row">
            <div class="col-4 text-left">
                    <div class="footer-menu__icon"><?= Html::img( '@web/img/book.svg',['alt'=>'','class'=>'cursor-pointer']) ?>
                    </div>
                    <div class="footer-menu__title">
                        <h3> О компании </h3>
                    </div>
                    <div class="footer-menu__items">
                        <ul class="d-flex flex-column">
                        <li><a href="" class="a">О нас</a></li>
                        <li><a href="" class="a">Адреса</a></li>
                        <li><a href="" class="a">Партнёры</a></li>
                        <li><a href="" class="a">Услуги</a></li>
                        <li><a href="" class="a">Работа</a></li>
                    </ul>
                    </div>
                </div>
            <div class="col-4 text-left">
                <div class="footer-menu__icon">
                    <?= Html::img( '@web/img/busket_2.svg',['alt'=>'','class'=>'cursor-pointer']) ?>
                </div>
                <div class="footer-menu__title">
                    <h3>О интернет магазине </h3>
                </div>
                <div class="footer-menu__items">
                    <ul class="d-flex flex-column ">
                    <li><a href="" class="a">Доставка и оплата</a></li>
                    <li><a href="" class="a">Акции</a></li>
                    <li><a href="" class="a">Товары</a></li>
                    <li><a href="" class="a">Политика конфиденциальности</a></li>
                    <li><a href="" class="a">Правила</a></li>
                </ul>
                </div>
            </div>

            <div class="col-4 text-left">
               <div class="footer-menu__icon"> <?= Html::img( '@web/img/envelope.svg',['alt'=>'','class'=>'cursor-pointer']) ?>
               </div>
                <div class="footer-menu__title"><h3>Подписка на новости</h3>
                </div>
                <form class="subscription" action="">
                    <label for="email">Быть в курсе событий:</label>
                    <br>
                    <input type="email" id="email" placeholder="E-mail" class="subscription__email">
                    <input type="submit" value="Подписка" class="subscription__submit cursor-pointer">
                </form>
                <div class="social">
                    <p>Мы в соцсетях:</p>
                    <ul class="social__icons d-flex">
                        <li><a href=""><i class="fab fa-vk"></i></a> </li>
                        <li><a href=""><i class="fab fa-instagram"></i></a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</footer>
<?php
\yii\bootstrap\Modal::begin([
        'header' => '<h2>Корзина</h2>',
        'id' => 'basket-modal',
        'size'=>'modal-lg',
        'footer'=> '<button type="button" class="btn btn-default" data-dismiss="modal">Продолжить покупки</button> <a type="button" class="btn btn-success" href='.Url::to(['basket/view']).'> Оформить заказ</a>
  <button type="button" class="btn btn-danger clean-basket-btn">Очистить корзину</button>  ',
]);
\yii\bootstrap\Modal::end();

?>


<?php $this->endBody() ?>
</body>

</html>
<?php $this->endPage() ?>